/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pricelabel;

public class App {
    public static void main(String[] args) {

    }
    public String getPriceLabel(String itemName, Double price) {
        return "The price for item: " + itemName + " is " + price;
      }
    public static Object getGreeting() {
        return null;
    }

}
