/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package priceLabel.app.src.test.java.pricelabel;

import org.junit.Test;

import priceLabel.app.src.main.java.pricelabel.App;

import static org.junit.Assert.*;


public class AppTest {
    @Test
    public void testPriceAndName() {
        App classUnderTest = new App();
        assertEquals("outputs a string with price & item name",
                String.valueOf("The price for item: Coffee Machine is 15.99"),
                classUnderTest.getPriceLabel("Coffee Machine", 15.99));
    }
}